version: '3'

services:
  db:
    build: ./db/
    networks:
      - intern
    ports:
      - "27017:27017"

  backend:
    build: ./backend/
    networks:
      - intern
      - my_custom_network
    ports:
      - "3000:3000"
      - "224.0.0.251:5353:5353/udp"
    environment:
      SECRET: 'mydemosecret'

  frontend:
    build: ./frontend/
    ports:
      - "8888:80"
    restart: always
    volumes:
      - ./frontend/html:/usr/share/nginx/html
    networks:
      - intern
      # - traefik-proxy
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.mdc.rule=Host(`mdc.example.com`)"
    #   - "traefik.http.services.mdc.loadbalancer.server.port=80"
    #   - "traefik.http.routers.mdc.tls.certresolver=le"
    #   - "traefik.http.middlewares.mdc.redirectscheme.scheme=https"
    #   - "traefik.http.middlewares.mdc.redirectscheme.permanent=true"

  mongo-express:
      image: mongo-express
      restart: always
      # labels:
      #   - "traefik.enable=true"
      #   - "traefik.http.routers.express.rule=Host(`node.sesg.ch`) && PathPrefix(`/express`)"
      #   - "traefik.http.middlewares.strip-expresspath.stripprefix.prefixes=/express"
      #   - "traefik.http.routers.express.middlewares=strip-expresspath@docker"
      networks:
        - intern
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: mdcpassword
        ME_CONFIG_MONGODB_URL: mongodb://admin:mdcpassword@db:27017/
        # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


networks:
  # traefik-proxy:
      # external: true
  intern:
  my_custom_network:
      external: true